apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlNREF5TURRdwpPREl4TURoYUZ3MDBNREF5TURRd09ESXhNRGhhTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFDcklMMitjdGd2T0NMa3lNcGN1L0FWcEtuMzN0Q2M0TzJJVzE5aVM2ZWFiYTF3Z1NHQwpiY2FBcEsydmU2UHhaYWpYczRVN2Z1MFNyaGZ1TkkzeUswM2tkd0llOG1kcEl3RUZpYlJQRUNrdi9WWlRQZk5yCmk4Z01HdTRWQWtmcmhkRStuTGZOUm5kTTBTUEdSQlkxMkR4Zm1FdlNGbU45a09OMWJIa0EyUXA3K0xpNFEzcGMKR0VRbGJXMUNvdTNoK2IrZ2lJTy9zblZVZkdBV0gvZStmbWdnS1NLMUF1ZDdHdVB1T3h0ZDRJdkpoOEdsUGtKagppQ3pKb0hVajNzSnVwc2hrdm8rRWw1YUVoM0g3aGszU2ZlV1gzNWdhbHFGMWVkbytGT2xhdXpENmNiL0lXdks4ClBoWXhhWFVlWDFZMnZnY1REQ1A5ZjloMkRwOXc5MTFnbFlYVEFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlN6bEFYUEdqd3FVL3pBdW52cwp5QlA3c0J2R1VqQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFmRTZCYmlGNU9Tdy9VU1E1Q04vTTEycmRjNlFRCnhlK2NLa0JHRHNRaVB0b3FkbXBtVU9NcDBwTzVNVzkxS2o1VXFvTWVGNDVIMkdzN2JydnplV2xKT0wrN2tZcmQKLzg4NzNVM3lVMU1KVWlEbGRXUnBTREtyVXVCTkkzOWozbjRSOG1uRjJlOTdLaWpvUWdLV1B4WnpjZTJrZXN5RQo5NjFvekZnMDk1bUk0Q3hWeXA5aVVKQkk4L1pMMm8wd21NZ28zU2cwM2VtWHpHbDEreFJDRVd5eXo2S1NWZmZFCk5UcTdWM2NWeHpxcTFnTWQ0eDhpcHk4NW5jUkc5SU9PTXFPbFFFckEyOFdBenV5cGZubmtySFBxY0hrV2FpQjIKRmtMN0cxQjU4VGViTmNIVVBScTZNMFVuZ0ZVZ1F6b3ZTRm9ES3VNd2dtVTMvY3h1eTBacUF0N2I0dz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://bc5782ce-b658-48b1-be44-c337598fe761.k8s.ondigitalocean.com
  name: do-sgp1-k8s-hoang-cluster
contexts:
- context:
    cluster: do-sgp1-k8s-hoang-cluster
    user: do-sgp1-k8s-hoang-cluster-admin
  name: do-sgp1-k8s-hoang-cluster
current-context: do-sgp1-k8s-hoang-cluster
kind: Config
preferences: {}
users:
- name: do-sgp1-k8s-hoang-cluster-admin
  user:
    token: 21a5a93b30e19da7729b7f4769dc910922ffa9474ef83ce83c468ec7f0c90ced
