apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: do-api-admin-elove-mobi
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: "20M"
spec:
  rules:
    - host: devapi-admin.elove.mobi
      http:
        paths:
          - path: /
            backend:
              serviceName: nsa-api-gateway
              servicePort: 3000
