apiVersion: apps/v1
kind: Deployment
metadata:
  name: gate-way
  labels:
    app: gate-way
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gate-way
  template:
    metadata:
      labels:
        app: gate-way
    spec:
      containers:
        - name: gate-way
          image: docker.io/hoangnguyenminhhust/hust-boy:gate-way
          ports:
            - containerPort: 3000
