apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: kube-state-metrics
    app.kubernetes.io/version: v1.8.0
  name: kube-state-metrics
  namespace: kube-system
spec:
  clusterIP: None
  ports:
    - name: http-metrics
      port: 8084
      targetPort: http-metrics
    - name: telemetry
      port: 8083
      targetPort: telemetry
  selector:
    app.kubernetes.io/name: kube-state-metrics
