---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nspos-api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nspos-api-gateway
  template:
    metadata:
      labels:
        app: nspos-api-gateway
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "6969"
    spec:
      containers:
        - name: nspos-api-gateway
          image: docker.io/hoangnguyenminhhust/k8s:gate-way-dev
          resources:
            requests:
              cpu: 10m
          env:
            - name: PORT
              value: "3000"
            - name: FLUENTD_HOST
              value: fluentd.kube-logging
            - name: FLUENTD_PORT
              value: "24224"
            - name: NODEENV
              value: develop
            - name: JAEGER_AGENT_HOST
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.hostIP
            - name: JAEGER_AGENT_PORT
              value: "6832"
            - name: TRANSPORTER
              value: nats://example-nats-cluster:4222
            - name: REDIS_HOST
              value: redis-cluster
            - name: REDIS_PORT
              value: "6379"

---
apiVersion: v1
kind: Service
metadata:
  name: nspos-api-gateway
spec:
  selector:
    app: nspos-api-gateway
  ports:
    - port: 80
      targetPort: 80
