apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: basic-ingress
  namespace: ingress-nginx
spec:
  rules:
    - http:
        paths:

          - path: /2
            backend:
              serviceName: nspos-api-gateway
              servicePort: 80
          - path: /3
            backend:
              serviceName: hello-service
              servicePort: 8081


# apiVersion: extensions/v1beta1
# kind: Ingress
# metadata:
#   name: basic-ingress
# spec:
#   rules:
#   - host: lovecat.host
#     http:
#       paths:
#       - backend:
#           serviceName: hello-service
#           servicePort: 8081