apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: basic-ingress
spec:
  rules:
    - http:
        paths:
          - path: /1
            backend:
              serviceName: web
              servicePort: 8080
          - path: /2
            backend:
              serviceName: my-service-gate-way
              servicePort: 3000
          - path: /3
            backend:
              serviceName: app1
              servicePort: 8081
